package data_access;

import entities.Cuisine;
import entities.DietaryRestriction;
import entities.Intolerance;
import entities.Recipe;
import entities.User;
import use_case.approve_recipe.ApproveRecipeDataAccessInterface;
import use_case.recipe_generator.RecipeDataAccessInterface;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * A repository that shares recipe data between the Recipe Generator and Approve Recipe use cases.
 * This allows recipes generated by the generator to be available for approval.
 */
public class SharedRecipeRepository implements RecipeDataAccessInterface, ApproveRecipeDataAccessInterface {
    private final RecipeDataAccessInterface recipeGeneratorDao;
    private final Map<String, User> users;
    private List<Recipe> cachedRecipes;

    public SharedRecipeRepository(RecipeDataAccessInterface recipeGeneratorDao, Map<String, User> users) {
        this.recipeGeneratorDao = recipeGeneratorDao;
        this.users = users;
        this.cachedRecipes = new ArrayList<>();
    }

    // --- RecipeDataAccessInterface (Generator) ---

    @Override
    public List<Recipe> getRecipes(DietaryRestriction dietaryRestriction, 
                                   List<Intolerance> intolerances, 
                                   Cuisine cuisine, 
                                   Integer maxCalories, 
                                   Integer minProtein) {
        // Delegate to the generator DAO (e.g. Dummy or Real API)
        List<Recipe> generatedRecipes = recipeGeneratorDao.getRecipes(
                dietaryRestriction, intolerances, cuisine, maxCalories, minProtein
        );
        
        // Update the cache with the newly generated recipes
        this.cachedRecipes = generatedRecipes;
        
        return generatedRecipes;
    }

    // --- ApproveRecipeDataAccessInterface (Approver) ---

    @Override
    public List<Recipe> getAvailableRecipes() {
        // Return the recipes that were generated and cached
        return new ArrayList<>(cachedRecipes);
    }

    @Override
    public Recipe getRecipeById(int recipeId) {
        for (Recipe recipe : cachedRecipes) {
            if (recipe.getRecipeId() == recipeId) {
                return recipe;
            }
        }
        return null;
    }

    @Override
    public User getUser(String username) {
        return users.get(username);
    }

    @Override
    public void saveRecipeToUser(String username, Recipe recipe) {
        User user = users.get(username);
        if (user != null) {
            // Check if recipe is already in saved recipes
            boolean alreadySaved = user.getSavedRecipes().stream()
                    .anyMatch(r -> r.getRecipeId() == recipe.getRecipeId());

            if (!alreadySaved) {
                user.saveRecipe(recipe);
            }
        }
    }
}

